pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'bash -c "echo Hello from Bash"'
                sh 'bash -c "pwd"'
                sh 'bash -c "whoami"'
                sh 'bash -c "echo $PATH"'
                sh 'bash -c "echo $HOME"'
                sh 'bash -c "java -version"'
                sh 'bash -c "docker version"'
                // sh '''#!/bin/bash
                //     export SDKMAN_DIR="$HOME/.sdkman"
                //     [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
                //     # sdk version
                //     mvn -f java-tomcat-sample-docker/pom.xml clean package
                // '''
                // sh 'bash -c "sdk version"'
                // sh '''#!/bin/bash
                //      sdk version
                //     mvn -f java-tomcat-sample-docker/pom.xml clean package
                // '''
                sh 'mvn -f java-tomcat-sample-docker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build ./java-tomcat-sample-docker -t tomcatsamplewebapp:${env.BUILD_ID}"
                sh """
                    #!/bin/bash
                    # Remove all images except the one we just built
                    images_to_remove=\$(docker images --format '{{.Repository}}:{{.Tag}}' | grep -v '<none>:<none>' | grep -v "tomcatsamplewebapp:${env.BUILD_ID}")

                    # Check if there are images to remove
                    if [ -n "\$images_to_remove" ]; then
                    echo "Removing the following images:\n\$images_to_remove"
                    echo "\$images_to_remove" | xargs docker rmi -f
                    else
                    echo "No images to remove."
                    fi
                    """
            }
        }
        stage('Cleanup container') {
                steps {
                     // Check if the container exists (including stopped containers), and stop & remove it if it does
                        sh '''
                        if [ "$(docker ps -a -q -f name=tomcat-container)" ]; then
                            docker stop tomcat-container
                            docker rm tomcat-container
                        else
                            echo "Container 'tomcat-container' does not exist."
                        fi
                        '''
                }
            }
        stage('Cleanup') {
                steps {
                    // Start the Docker container
                    sh "docker run -d -p 8088:8080 --name tomcat-container tomcatsamplewebapp:${env.BUILD_ID}"
                }
            }


    }
}